### ISSUE TITLE
The project fails on grunt launch --open

### ISSUE THREAD

**Issue by rococtz** [codeBelt/StructureJS-Boilerplate#1]
Hi,

I tried downloading your project, ran `npm install` then `bower install` which went fine. Then I ran `grunt launch --open` and I get this error:

```
Running "browserify:buildTypeScript" (browserify) task
TypeScript error: src/assets/scripts/TestApp.ts(44,65): Error TS2339: Property 'find' does not exist on type 'JQuery'.
Warning: Error running grunt-browserify. Use --force to continue.
Aborted due to warnings.
```

Any clue what's happening?

**Comment by codeBelt** [comment]
Since TypeScript is always changing it seems we need to use [typings](https://github.com/typings/typings) now. I've updated the [TypeScript - ES6 Modules](https://github.com/codeBelt/StructureJS-Boilerplate/tree/typescript-es6) branch and added the **typings.json** file.

Now you will need install  [typings](https://github.com/typings/typings) (`npm install typings --global`) and when you use the boilerplate you will do:

`
npm install && bower install && typings install
`

On a side note I've moved away from grunt to gulp and I have a boilerplate generator you should checkout [slush project](https://github.com/codeBelt/slush-project)
